// LoggingViewModel.cs
//
// Author:
//       Sales Alencar <lopesdealencar@gmail.com>
//
// Copyright (c) 2018 MIT
using System;
namespace LoggingBlock.ViewModels
{
	/// <summary>
	/// Model that represents a logging information to client blocks. The structure of this ViewModel are:
	/// | Name | Type | Explanation | Example | 
	/// | ---- | ---- | ----------- | ------- |
	/// | Id | string | Autogenerated Id of logging message. This property is ignored when adding a new log entry | 6d598109-4f06-40ed-b6f0-33e26b1f53e7 | 
	/// | Message | string | Message information that want to be logged | *any message* |
	/// | Type | string | Type of message | Possible options are: <value>Info</value>, <value>Warning</value>, <value>Error</value> or <value>Fatal</value> |
	/// | BlockOrigin | string | Client block name | AuthenticationBlock, ChatBlock, etc. |
	/// </summary>
	public class LoggingBlockViewModel
	{
		
		public string Id { get; set; }

		public string Message { get; set; }

		public string Type { get; set; }

		public string BlockOrigin { get; set; }

	}
}
